version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://root:my-secret-pw@db/mydb
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
